---
- name: CREATE DIRECTORY & COPY FILES
  hosts: jennode100
  remote_user: root
  tasks:
    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/docker
        state: directory
        mode: "0755"      

    - name: COPY DOCKERFILE
      copy:
        src: ../Dockerfile
        dest: /opt/docker

    - name: COPY WAR FILE
      command: sudo scp -r root@172.31.45.193:/var/lib/jenkins/workspace/test123/webapp/target/webapp.war /opt/docker
