---
- name: CREATE DIRECTORY & COPY FILES
  hosts: localhost
  tasks:
    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/test
        state: directory
        mode: "0644"      

    - name: COPY DOCKERFILE
      copy:
        src: ../Dockerfile
        dest: /opt/docker

    
